### ISSUE TITLE
Doesn't work with Ninja in Release configuration.

### ISSUE THREAD

**Issue by novikov-alexander-zz** [forexample/hunter-simple#6]
This example doesn't work with Ninja build system in "RelWithDebInfo" configuration.

I opened repositody in the VS2017 developer command promt and wrote:
```
mkdir build
cd build
cmake -G "Ninja" -DCMAKE_BUILD_TYPE="RelWithDebInfo"
```

Configuration was done successfully.
Then I wrote:
`ninja`

The linker returned a lot of errors:

> LINK Pass 1: command "C:\PROGRA\~2\MIB055\~1\2017\COMMUN\~1\VC\Tools\MSVC\1416\~1.270\bin\Hostx86\x86\link.exe /nologo CMakeFiles\simple.dir\simple.cpp.obj /out:simple.exe /implib:simple.lib /pdb:simple.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console C:\.hunter\_Base\4189bbd\f8a9f63\68bb0e6\Install\lib\gtest_maind.lib C:\.hunter\_Base\4189bbd\f8a9f63\68bb0e6\Install\lib\gtestd.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\simple.dir/intermediate.manifest CMakeFiles\simple.dir/manifest.res" failed (exit code 1120) with the following output:
> gtestd.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in simple.cpp.obj
> gtestd.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in simple.cpp.obj
> gtest_maind.lib(gtest_main.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in simple.cpp.obj
> gtest_maind.lib(gtest_main.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in simple.cpp.obj
> LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
> gtestd.lib(gtest-all.cc.obj) : error LNK2019: unresolved external symbol __imp___invalid_parameter referenced in function "void * __cdecl std::_Allocate_manually_vector_aligned<struct std::_Default_allocate_traits>(unsigned int)" (??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPAXI@Z)
> gtestd.lib(gtest-all.cc.obj) : error LNK2019: unresolved external symbol __imp___calloc_dbg referenced in function "char * __cdecl std::_Maklocstr<char>(char const *,char *,struct _Cvtvec const &)" (??$_Maklocstr@D@std@@YAPADPBDPADABU_Cvtvec@@@Z)
> gtest_maind.lib(gtest_main.cc.obj) : error LNK2001: unresolved external symbol __imp___calloc_dbg
> gtestd.lib(gtest-all.cc.obj) : error LNK2019: unresolved external symbol __imp___CrtDbgReport referenced in function "void * __cdecl std::_Allocate_manually_vector_aligned<struct std::_Default_allocate_traits>(unsigned int)" (??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPAXI@Z)
> simple.exe : fatal error LNK1120: 3 unresolved externals

It seems like linker tries to link to debug version of GTest by some reasons.

**Comment by ruslo** [comment]
By default, Hunter will build Debug and Release. I guess it's falling to Debug if an exact match was not found. Try to add `HUNTER_CONFIGURATION_TYPES=RelWithDebInfo`:
- https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-configuration-types

**Comment by novikov-alexander-zz** [comment]
Awesome! Thank you!
The problem is that Visual Studio uses RelWithDebInfo configuration instead Release by default while working with CMake projects.
May it be better to add RelWithDebInfo configuration to the example?

**Comment by ruslo** [comment]
> The problem is that Visual Studio uses RelWithDebInfo configuration instead Release by default while working with CMake projects

If you use Visual Studio generator, by default configuration types list will be `Debug;Release;MinSizeRel;RelWithDebInfo`. As far as I can see you're using Ninja generator and explicitly set the build type to `RelWithDebInfo`.

**Comment by novikov-alexander** [comment]
I've just opened the project folder in the Visual Studio 2019. 
It uses ninja by default.

**Comment by novikov-alexander-zz** [comment]
I've tried to run ninja explicitly just for test simplification. 
I initially tried to build a project using Visual Studio 2019. 
Visual Studio 2019 uses Ninja generator by default. 
If I just clone the repo and open the source folder in the Visual Studio 2019 (File->Open->Folder) it tries to build the project in RelWithDebInfo configuration.
Why it happens?
Should I create a new issue (Doesn't work with VS2019 in Release configuration.) :-)

**Comment by ruslo** [comment]
> open the source folder in the Visual Studio 2019 (File->Open->Folder) it tries to build the project in RelWithDebInfo configuration

I think it's a user specific. I haven't touched anything, and it's `Debug` by default for me:
```
>------ Build All started: Project: hunter-simple, Configuration: x64-Debug (default) ------
```

**Comment by ruslo** [comment]
Closing inactive discussion.
